# Generated by Django 2.1.3 on 2019-04-24 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_title', models.CharField(max_length=100)),
                ('an_price', models.CharField(max_length=100)),
                ('an_content', models.TextField(max_length=1000)),
                ('an_num_street', models.CharField(max_length=40)),
                ('an_street', models.CharField(max_length=40)),
                ('an_city', models.CharField(max_length=40)),
                ('an_postalcode', models.CharField(max_length=10)),
                ('an_country', models.CharField(max_length=40)),
                ('an_thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='category.Category')),
            ],
        ),
    ]
