# Generated by Django 2.1.3 on 2019-04-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='an_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='an_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='an_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='an_num_street',
            new_name='num_street',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='an_postalcode',
            new_name='postalcode',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='an_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='an_street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='an_thumb',
            new_name='thumb',
        ),
    ]
