# Generated by Django 2.1.3 on 2019-04-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190424_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='an_title',
            new_name='title',
        ),
    ]
