# Generated by Django 2.1.3 on 2019-04-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190424_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='an_type',
            field=models.CharField(default='Offres', max_length=100),
        ),
    ]
