# Generated by Django 2.1.3 on 2019-04-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_an_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Offres', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='an_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='post.PostType'),
        ),
    ]
