# Generated by Django 2.1.3 on 2019-04-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190424_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.FileField(default=None, upload_to='media'),
        ),
    ]
