# Generated by Django 2.1.3 on 2019-04-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20190425_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_thee',
            new_name='image_three',
        ),
    ]
